experiment_name: "MNIST Training"

mode: "train"

train:
  is_resume: false
  checkpoint_dir: ./checkpoints
  checkpoint_name: checkpoint_5_accuracy=0.9884.pt
  n_saved: 2
  epochs: 10

aim:
  run_hash: d517329f056c4867a2ed66ca