mode: "train"

train:
  is_resume: false
  training_checkpoint_dir: ./training_checkpoints
  training_checkpoint_name: checkpoint_2_accuracy=0.9824.pt
  n_saved: 2
  model_checkpoint_dir: ./model_checkpoints
  epochs: 6